[project]
name = "mltools-p1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dateparser>=1.2.1",
    "fastapi[standard]>=0.115.8",
    "openai>=1.63.0",
]
